INSERT INTO item (locName, iName, iWeight, iValue, iDesc) VALUES
('Whiterun','Blade of Whiterun',50.000000,150,'Badge of office for the Thane of Whiterun.'),
('Abandoned Prison',' Iron Shackles',2.500000,30,' Rusty restraints from a forgotten cell.'),
('Alftand',' Dwemer Cog',1.800000,45,' Salvaged from the ancient dwarven ruins.'),
('Angis Camp',' Hunters Bow',3.200000,60,' Crafted by the skilled archer Angi.'),
('Anises Cabin',' Hagraven Feather',0.300000,20,' A mystical ingredient for dark rituals.'),
('Arcwind Point',' Frost Troll Pelt',4.000000,70,' Trophy from a fierce battle atop the peak.'),
('Autumnshade Clearing',' Moonflower Nectar',0.100000,10,' Glows softly under the moonlight.'),
('Avanchnzel',' Dwarven Centurion Core',8.500000,120,' The heart of an ancient automaton.'),
('Bannermist Tower',' Guards Helm',1.200000,40,' Worn by the vigilant tower sentinels.'),
('Bards Leap Summit',' Lute Strings',0.100000,5,' Broken strings from a bards tragic fall.'),
('Battle-Born Farm',' Wheat Sack',1.000000,25,' Harvested from the fertile fields.'),
('Bilegulch Mine',' Orichalcum Ore',5.800000,80,' Mined deep within the treacherous tunnels.'),
('Black-Briar Lodge',' Velvet Wine Bottle',1.500000,50,' A luxurious vintage from Mavens cellar.'),
('Bleak Falls Barrow',' Dragonstone Tablet',3.500000,90,' Inscribed with ancient dragon lore.'),
('Bleakwind Basin',' Sabre Cat Claw',0.400000,30,' Extracted from a fearsome predator.'),
('Blind Cliff Cave',' Chaurus Egg Sac',0.200000,15,' Contains wriggling chaurus larvae.'),
('Bloated Mans Grotto',' Spriggan Sap',0.500000,35,' Harvested from the mystical grottos trees.'),
('Bloodlet Throne',' Vampire Dust',0.100000,5,' Essence of the undead for dark rituals.'),
('Blue Palace',' Jarls Crown',2.000000,70,' Adorned by the ruler of Solitude.'),
('Bonestrewn Crest',' Mammoth Tusk',6.200000,100,' Ivory harvested from a fallen giants beast.'),
('Boulderfall Cave',' Troll Skull',3.800000,65,' Gruesome trophy from a cave-dwelling troll.'),
('Brandy-Mug Farm',' Honey Jar',0.800000,30,' Sweet nectar collected from busy bees.'),
('Brinewater Grotto',' Pearl Oyster',0.300000,20,' Conceals a lustrous pearl within its shell.'),
('Broken Helm Hollow',' Bandit Leaders Dagger',1.200000,45,' Stolen blade from a fallen outlaw chief.'),
('Broken Limb Camp',' Giants Toe',4.500000,75,' Colossal ingredient for alchemical experiments.');
