INSERT INTO location VALUES
('Abandoned Prison'),
('Abandoned Shack'),
('Alchemists Shack'),
('Alftand'),
('Ancients Ascent'),
('Angas Mill'),
('Angarvunde'),
('Angis Camp'),
('Anises Cabin'),
('Ansilvund'),
('Arcwind Point'),
('Autumnshade Clearing'),
('Autumnwatch Tower'),
('Avanchnzel'),
('Bannermist Tower'),
('Bards Leap Summit'),
('Battle-Born Farm'),
('Bilegulch Mine'),
('Black-Briar Lodge'),
('Bleak Falls Barrow (Location)'),
('Bleakcoast Cave'),
('Bleakwind Basin'),
('Bleakwind Bluff'),
('Blind Cliff Cave'),
('Blizzard Rest'),
('Bloated Mans Grotto'),
('Bloodlet Throne'),
('Blue Palace'),
('Bonestrewn Crest'),
('Boulderfall Cave'),
('Brandy-Mug Farm'),
('Brinewater Grotto'),
('Broken Fang Cave'),
('Broken Helm Hollow'),
('Broken Limb Camp'),
('Broken Oar Grotto'),
('Broken Tower Redoubt'),
('Bronze Water Cave'),
('Brood Cavern'),
('Brucas Leap Redoubt'),
('Bthardamz'),
('Chillifurrow Farm'),
('Chillwind Depths'),
('Clearpine Pond'),
('Clearspring Tarn'),
('Cliffside Retreat'),
('Crabbers Shanty'),
('Cracked Tusk Keep'),
('Cradle Stone Tower'),
('Cradlecrush Rock'),
('Cragslane Cavern'),
('Cragwallow Slope'),
('Cronvangr Cave'),
('Crystaldrift Cave');
